### ISSUE TITLE
add ru_ru lang

### ISSUE THREAD

**Issue by CoringPlay** [anviaan/GlowInkPlus#1]
{
  "ItemGroup.glow_ink_plus.glow_ink_sac": "Glow Ink Plus Mod",

  "block.glow_ink_plus.glow_white_wool": "Светящаяся белая шерсть",
  "block.glow_ink_plus.glow_orange_wool": "Светящаяся оранжевая шерсть",
  "block.glow_ink_plus.glow_magenta_wool": "Светящаяся пурпурная шерсть",
  "block.glow_ink_plus.glow_light_blue_wool": "Светящаяся светло-голубая шерсть",
  "block.glow_ink_plus.glow_yellow_wool": "Светящаяся желтая шерсть",
  "block.glow_ink_plus.glow_lime_wool": "Светящаяся лаймовая шерсть",
  "block.glow_ink_plus.glow_pink_wool": "Светящаяся розовая шерсть",
  "block.glow_ink_plus.glow_gray_wool": "Светящаяся серая шерсть",
  "block.glow_ink_plus.glow_light_gray_wool": "Светящаяся светло-серая шерсть",
  "block.glow_ink_plus.glow_cyan_wool": "Светящаяся голубая шерсть",
  "block.glow_ink_plus.glow_purple_wool": "Светящаяся фиолетовая шерсть",
  "block.glow_ink_plus.glow_blue_wool": "Светящаяся голубая шерсть",
  "block.glow_ink_plus.glow_brown_wool": "Светящаяся коричневая шерсть",
  "block.glow_ink_plus.glow_green_wool": "Светящаяся зеленая шерсть",
  "block.glow_ink_plus.glow_red_wool": "Светящаяся красная шерсть",
  "block.glow_ink_plus.glow_black_wool": "Светящаяся чёрная шерсть",

  "block.glow_ink_plus.glow_white_carpet": "Светящийся белый ковёр",
  "block.glow_ink_plus.glow_orange_carpet": "Светящийся оранжевый ковёр",
  "block.glow_ink_plus.glow_magenta_carpet": "Светящийся пурпурный ковёр",
  "block.glow_ink_plus.glow_light_blue_carpet": "Светящийся светло-голубой ковёр",
  "block.glow_ink_plus.glow_yellow_carpet": "Светящийся желтый ковёр",
  "block.glow_ink_plus.glow_lime_carpet": "Светящийся лаймовый ковёр",
  "block.glow_ink_plus.glow_pink_carpet": "Светящийся розовый ковёр",
  "block.glow_ink_plus.glow_gray_carpet": "Светящийся серый ковёр",
  "block.glow_ink_plus.glow_light_gray_carpet": "Светящийся светло-серый ковёр",
  "block.glow_ink_plus.glow_cyan_carpet": "Светящийся голубой ковёр",
  "block.glow_ink_plus.glow_purple_carpet": "Светящийся фиолетовый ковёр",
  "block.glow_ink_plus.glow_blue_carpet": "Светящийся синий ковёр",
  "block.glow_ink_plus.glow_brown_carpet": "Светящийся коричневый ковёр",
  "block.glow_ink_plus.glow_green_carpet": "Светящийся зеленый ковёр",
  "block.glow_ink_plus.glow_red_carpet": "Светящийся красный ковёр",
  "block.glow_ink_plus.glow_black_carpet": "Светящийся чёрный ковёр"
}

**Comment by anviaan** [comment]
done
